# fly.toml app configuration file generated for nestjs-techniques-firebase-admin on 2025-05-10T20:21:58Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'nestjs-techniques-firebase-admin'
primary_region = 'gru'

[build]

[http_service]
  internal_port = 5672
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
